name: cdth_fhir
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - pip
  - matplotlib
  - python-dateutil
  - requests
  - seaborn
  - pip:
    - git+https://github.com/smart-on-fhir/client-py.git
